### ISSUE TITLE
Type used only exist in PowerShell Core

### ISSUE THREAD

**Issue by johlju** [pcgeek86/PSGitHub#55] opened 2019-09-15 13:49 UTC
The type `[Microsoft.PowerShell.Commands.HttpResponseException]` does not exist in Windows PowerShell. See https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.httpresponseexception?view=pscore-6.2.0

https://github.com/pcgeek86/PSGitHub/blob/f800ce0ae31ff7c5f36d6548a8515755a52fd9b6/Functions/Private/Invoke-GitHubApi.ps1#L95

- [x] Verison of PowerShell you're using: 5.1
- [x] PowerShell host you're using (eg. Console Host, ISE, Visual Studio): Console
- [x] Operating system you're running: Windows 10 Insider 
- [x] Version of PSGitHub you're using (use `Get-Module -Name PSGitHub`): 0.15.178

**Comment by johlju** [comment] 2019-09-15 13:49
Either move the module over to PowerShell Core only, or change to another type. 🤔

**Comment by felixfbecker** [comment] 2019-09-15 18:13
Duplicate of #53

**Closed as completed by felixfbecker** 2019-09-15 18:13 UTC
